name: cowabunga CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: install NPM dependencies
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting
        run: npm run lint

      - name: unit testing
        run: npm run test
